apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: prod
  labels:
    app: myapp
spec:
  containers:
  - name: test1
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    -  containerPort: 80
  - name: test2
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
-  containerPort: 80
